/**
 * @name 125924010081004
*/
Select T_EAM_EQUIPMENT_UNIT_EVENTS_1.EUE_ID, T_EAM_EQUIPMENT_UNIT_EVENTS_1.EUE_EQUIPMENT_UNIT, T_EAM_EQUIPMENT_UNIT_EVENTS_1.EUE_EVENT_TIME, 
T_EAM_EQUIPMENT_UNIT_EVENTS_1.EUE_IS_STARTED 
From EAS.EAM_EQUIPMENT_UNIT_EVENTS T_EAM_EQUIPMENT_UNIT_EVENTS_1
 Where :Param1 = T_EAM_EQUIPMENT_UNIT_EVENTS_1.EUE_EQUIPMENT_UNIT