/**
 * @name 124904940312527
*/
SELECT T_ENUMERATIONS_1.ID, T_ENUMERATIONS_1.ISGROUP, T_ENUMERATIONS_1.GROUP_ID, T_ENUMERATIONS_1.NAME FROM EAS.ENUMERATIONS T_ENUMERATIONS_1 WHERE T_ENUMERATIONS_1.GROUP_ID IS NULL