/**
 * @name 124808559102902752
*/
SELECT T_MTD_ENTITIES_1.MDENT_ID, T_MTD_ENTITIES_1.MDENT_NAME, T_MTD_ENTITIES_1.MDENT_TYPE, T_MTD_ENTITIES_1.MDENT_CONTENT_TXT, T_MTD_ENTITIES_1.MDENT_CONTENT_DATA, T_MTD_ENTITIES_1.TAG1, T_MTD_ENTITIES_1.TAG2, T_MTD_ENTITIES_1.TAG3, T_MTD_ENTITIES_1.MDENT_PARENT_ID, T_MTD_ENTITIES_1.MDENT_ORDER FROM EAS.MTD_ENTITIES T_MTD_ENTITIES_1