/**
 * @name 132194567350164
*/
//  Для документирования грида. Убрать лишнее, оставшемуся дать краткое описание
  
  //свойства
  accessibleContext
  actionMap
  alignmentX
  alignmentY
  ancestorListeners
  autoscrolls
  background
  backgroundSet
  baselineResizeBehavior
  border
  bottomLeftTable
  bottomRightTable
  bounds
  class
  colorModel
  columnModel
  componentCount
  componentListeners
  componentOrientation
  componentPopupMenu
  components
  containerListeners
  currentRow
  cursor
  cursorSet
  datamodel
  debugGraphicsOptions
  deepModel
  deletable
  designInfo
  displayable
  doubleBuffered
  dropTarget
  editable
  enabled
  focusCycleRoot
  focusCycleRootAncestor
  focusListeners
  focusOwner
  focusTraversable
  focusTraversalKeysEnabled
  focusTraversalPolicy
  focusTraversalPolicyProvider
  focusTraversalPolicySet
  focusable
  focusedTable
  font
  fontSet
  foreground
  foregroundSet
  graphics
  graphicsConfiguration
  gridColor
  height
  hierarchyBoundsListeners
  hierarchyListeners
  ignoreRepaint
  inheritsPopupMenu
  inputContext
  inputMap
  inputMethodListeners
  inputMethodRequests
  inputVerifier
  insertable
  insets
  keyListeners
  layout
  lightweight
  locale
  location
  locationOnScreen
  managingFocus
  maximumSize
  maximumSizeSet
  minimumSize
  minimumSizeSet
  mouseListeners
  mouseMotionListeners
  mousePosition
  name
  nextFocusableComponent
  oddRowsColor
  opaque
  optimizedDrawingEnabled
  paintingForPrint
  paintingTile
  parent
  peer
  preferredSize
  preferredSizeSet
  propertyChangeListeners
  registeredKeyStrokes
  requestFocusEnabled
  rootPane
  rowSorter
  rowsHeight
  rowsHeight
  rowsSelectionModel
  selection
  showHorizontalLines
  showOddRowsInOtherColor
  showVerticalLines
  showing
  size
  style
  toolTipText
  toolkit
  topLeftTable
  topLevelAncestor
  topRightTable
  transferHandler
  treeLock
  uI
  uIClassID
  unaryLinkField
  valid
  validateRoot
  verifyInputWhenFocusTarget
  vetoableChangeListeners
  visible
  visibleRect
  width
  x
  y
  //методы
  IsRuntime()
  IsUpdating()
  SetEditingValue(Object)
  SetRuntime(boolean)
  action(Event,Object)
  add(Component)
  add(Component,Object)
  add(Component,Object,int)
  add(Component,int)
  add(PopupMenu)
  add(String,Component)
  addAncestorListener(AncestorListener)
  addComponentListener(ComponentListener)
  addContainerListener(ContainerListener)
  addFocusListener(FocusListener)
  addHierarchyBoundsListener(HierarchyBoundsListener)
  addHierarchyListener(HierarchyListener)
  addInputMethodListener(InputMethodListener)
  addKeyListener(KeyListener)
  addMouseListener(MouseListener)
  addMouseMotionListener(MouseMotionListener)
  addMouseWheelListener(MouseWheelListener)
  addNotify()
  addPropertyChangeListener(PropertyChangeListener)
  addPropertyChangeListener(String,PropertyChangeListener)
  addVetoableChangeListener(VetoableChangeListener)
  applyBackground()
  applyComponentOrientation(ComponentOrientation)
  applyForeground()
  areFocusTraversalKeysSet(int)
  beginUpdate()
  bounds()
  checkImage(Image,ImageObserver)
  checkImage(Image,int,int,ImageObserver)
  clearSelection()
  computeVisibleRect(Rectangle)
  configure()
  contains(Point)
  contains(int,int)
  countComponents()
  createImage(int,int)
  createPropertyObjectInstance(String)
  createToolTip()
  createVolatileImage(int,int)
  createVolatileImage(int,int,ImageCapabilities)
  deliverEvent(Event)
  disable()
  dispatchEvent(AWTEvent)
  doLayout()
  enable()
  enable(boolean)
  enableInputMethods(boolean)
  endUpdate()
  ensureFetched(ScriptableRowset,Field,Object)
  equals(Object)
  fillByRowset(ScriptableRowset)
  findComponentAt(Point)
  findComponentAt(int,int)
  findSomething()
  firePropertyChange(String,boolean,boolean)
  firePropertyChange(String,byte,byte)
  firePropertyChange(String,char,char)
  firePropertyChange(String,double,double)
  firePropertyChange(String,float,float)
  firePropertyChange(String,int,int)
  firePropertyChange(String,long,long)
  firePropertyChange(String,short,short)
  getAccessibleContext()
  getActionForKeyStroke(KeyStroke)
  getActionMap()
  getAlignmentX()
  getAlignmentY()
  getAncestorListeners()
  getAutoscrolls()
  getBackground()
  getBaseline(int,int)
  getBaselineResizeBehavior()
  getBorder()
  getBottomLeftTable()
  getBottomRightTable()
  getBounds()
  getBounds(Rectangle)
  getClass()
  getClientProperty(Object)
  getColorModel()
  getColumnModel()
  getComponent(int)
  getComponentAt(Point)
  getComponentAt(int,int)
  getComponentCount()
  getComponentListeners()
  getComponentOrientation()
  getComponentPopupMenu()
  getComponentZOrder(Component)
  getComponents()
  getConditionForKeyStroke(KeyStroke)
  getContainerListeners()
  getCurrentRow()
  getCursor()
  getDatamodel()
  getDebugGraphicsOptions()
  getDeepModel()
  getDesignInfo()
  getDropTarget()
  getFocusCycleRootAncestor()
  getFocusListeners()
  getFocusTraversalKeys(int)
  getFocusTraversalKeysEnabled()
  getFocusTraversalPolicy()
  getFocusedTable()
  getFont()
  getFontMetrics(Font)
  getForeground()
  getGraphics()
  getGraphicsConfiguration()
  getGridColor()
  getHeight()
  getHierarchyBoundsListeners()
  getHierarchyListeners()
  getIgnoreRepaint()
  getInheritsPopupMenu()
  getInputContext()
  getInputMap()
  getInputMap(int)
  getInputMethodListeners()
  getInputMethodRequests()
  getInputVerifier()
  getInsets()
  getInsets(Insets)
  getKeyListeners()
  getLayout()
  getListeners(Class)
  getLocale()
  getLocation()
  getLocation(Point)
  getLocationOnScreen()
  getMaximumSize()
  getMinimumSize()
  getMouseListeners()
  getMouseMotionListeners()
  getMousePosition()
  getMousePosition(boolean)
  getMouseWheelListeners()
  getName()
  getNextFocusableComponent()
  getOddRowsColor()
  getParent()
  getPeer()
  getPopupLocation(MouseEvent)
  getPreferredSize()
  getPropertyChangeListeners()
  getPropertyChangeListeners(String)
  getRegisteredKeyStrokes()
  getRootPane()
  getRowSorter()
  getRowsHeight()
  getRowsSelectionModel()
  getSelection()
  getSize()
  getSize(Dimension)
  getStyle()
  getTableByViewCell(int,int)
  getToolTipLocation(MouseEvent)
  getToolTipText()
  getToolTipText(MouseEvent)
  getToolkit()
  getTopLeftTable()
  getTopLevelAncestor()
  getTopRightTable()
  getTransferHandler()
  getTreeLock()
  getUI()
  getUIClassID()
  getVerifyInputWhenFocusTarget()
  getVetoableChangeListeners()
  getVisibleRect()
  getWidth()
  getX()
  getY()
  gotFocus(Event,Object)
  grabFocus()
  handleEvent(Event)
  hasFocus()
  hashCode()
  hide()
  imageUpdate(Image,int,int,int,int,int)
  index2Row(int)
  initializeDesign()
  insets()
  inside(int,int)
  invalidate()
  isAncestorOf(Component)
  isBackgroundSet()
  isCurrentRow(Row)
  isCursorSet()
  isDeletable()
  isDisplayable()
  isDoubleBuffered()
  isEditable()
  isEnabled()
  isFocusCycleRoot()
  isFocusCycleRoot(Container)
  isFocusOwner()
  isFocusTraversable()
  isFocusTraversalPolicyProvider()
  isFocusTraversalPolicySet()
  isFocusable()
  isFontSet()
  isForegroundSet()
  isInsertable()
  isLightweight()
  isManagingFocus()
  isMaximumSizeSet()
  isMinimumSizeSet()
  isOpaque()
  isOptimizedDrawingEnabled()
  isPaintingForPrint()
  isPaintingTile()
  isPreferredSizeSet()
  isRequestFocusEnabled()
  isShowHorizontalLines()
  isShowOddRowsInOtherColor()
  isShowVerticalLines()
  isShowing()
  isTreeConfigured(DbGridTreeDesignInfo)
  isValid()
  isValidateRoot()
  isVisible()
  keyDown(Event,int)
  keyUp(Event,int)
  layout()
  list()
  list(PrintStream)
  list(PrintStream,int) 
  list(PrintWriter)
  list(PrintWriter,int)
  locate(int,int)
  location()
  lostFocus(Event,Object)
  makeVisible(Object)
  makeVisible(Object,boolean)
  makeVisible(Row)
  makeVisible(Row,boolean)
  minimumSize()
  mouseDown(Event,int,int)
  mouseDrag(Event,int,int)
  mouseEnter(Event,int,int)
  mouseExit(Event,int,int)
  mouseMove(Event,int,int)
  mouseUp(Event,int,int)
  move(int,int)
  paint(Graphics)
  paintAll(Graphics)
  paintComponents(Graphics)
  paintImmediately(Rectangle)
  paintImmediately(int,int,int,int)
  postEvent(Event)
  preferredSize()
  prepareImage(Image,ImageObserver)
  prepareImage(Image,int,int,ImageObserver)
  print(Graphics)
  printAll(Graphics)
  printComponents(Graphics)
  propertyChange(PropertyChangeEvent)
  putClientProperty(Object,Object)
  registerKeyboardAction(ActionListener,KeyStroke,int)
  registerKeyboardAction(ActionListener,String,KeyStroke,int)
  remove(Component)
  remove(MenuComponent)
  remove(int)
  removeAll()
  removeAncestorListener(AncestorListener)
  removeComponentListener(ComponentListener)
  removeContainerListener(ContainerListener)
  removeFocusListener(FocusListener)
  removeHierarchyBoundsListener(HierarchyBoundsListener)
  removeInputMethodListener(InputMethodListener)
  removeKeyListener(KeyListener)
  removeMouseListener(MouseListener)
  removeMouseMotionListener(MouseMotionListener)
  removeMouseWheelListener(MouseWheelListener)
  removeNotify()
  removePropertyChangeListener(PropertyChangeListener)
  removePropertyChangeListener(String,PropertyChangeListener)
  removeVetoableChangeListener(VetoableChangeListener)
  repaint()
  repaint(Rectangle)
  repaint(int,int,int,int)
  repaint(long)
  repaint(long,int,int,int,int)
  requestDefaultFocus()
  requestFocus()
  requestFocus(boolean)
  requestFocusInWindow()
  resetKeyboardActions()
  reshape(int,int,int,int)
  resize(Dimension)
  resize(int,int)
  revalidate()
  row2Index(Row)
  scrollRectToVisible(Rectangle)
  selectRow(Object)
  selectRow(Row)
  setBounds(int,int,int,int)
  setComponentZOrder(Component,int)
  setFocusTraversalKeys(int,Set)
  setInputMap(int,InputMap)
  setLocation(int,int)
  setSize(int,int)
  show()
  show(boolean)
  size()
  toString()
  transferFocus()
  transferFocusBackward()
  transferFocusDownCycle()
  transferFocusUpCycle()
  try2CancelAnyEditing()
  try2StopAnyEditing()
  unregisterKeyboardAction(KeyStroke)
  unselectRow(Object)
  unselectRow(Row)
  update(Graphics)
  updateUI()
  validate()