/**
 * Do not edit this file manually, it will be overwritten by
 * Platypus Application Designer.
 */
// this === global
if(!this.P)
    this.P = {};
P.ready = function() {
    P.require(['ambigous_changes_semi_writable'], function(){
        var m = new ambigous_changes_semi_writable();
        m.execute();
    }, function(e){
        P.Logger.severe(e);
    });
};
