/**
 * @name 131408499123740
*/
Select t.MDENT_NAME, t.MDENT_ID, t.MDENT_ORDER, 
t.MDENT_PARENT_ID, t.MDENT_TYPE, (t.MDENT_ID / 10000000000000000) TEST_FLOAT, 
TO_CHAR(SYSDATE, 'HH24:MI:SS YYYY/MM/DD') TEST_DATE 
From MTD_ENTITIES t
 Where ((:PARENT_ENTITY_ID = t.MDENT_PARENT_ID
 and :PARENT_ENTITY_ID is not null) or (:PARENT_ENTITY_ID is null
 and t.MDENT_PARENT_ID is null))
 Order by t.MDENT_NAME asc