/**
 * @name 126872823407204
*/
SELECT T_DELAWARE_HIGHWAYS_1.DELAWARE_HIGHWAYS_ID, T_DELAWARE_HIGHWAYS_1.THE_GEOM, T_DELAWARE_HIGHWAYS_1.TYPE, T_DELAWARE_HIGHWAYS_1.NAME, T_DELAWARE_HIGHWAYS_1.ONEWAY FROM DELAWARE_HIGHWAYS T_DELAWARE_HIGHWAYS_1 WHERE ((:LOADHIGHWAYS!=0) AND (SDO_FILTER(T_DELAWARE_HIGHWAYS_1.THE_GEOM, SDO_GEOMETRY(2003, NULL, NULL, SDO_ELEM_INFO_ARRAY(1, 1003, 3), SDO_ORDINATE_ARRAY(:X1, :Y1, :X2, :Y2)))='TRUE')) OR (T_DELAWARE_HIGHWAYS_1.TYPE='primary')