/**
 * @name 126872808477399
*/
SELECT T_DELAWARE_POINTS_1.DELAWARE_POINTS_ID, T_DELAWARE_POINTS_1.THE_GEOM, T_DELAWARE_POINTS_1.CATEGORY, T_DELAWARE_POINTS_1.NAME FROM DELAWARE_POINTS T_DELAWARE_POINTS_1 WHERE (:LOADPOINTS!=0) AND (SDO_FILTER(T_DELAWARE_POINTS_1.THE_GEOM, SDO_GEOMETRY(2003, NULL, NULL, SDO_ELEM_INFO_ARRAY(1, 1003, 3), SDO_ORDINATE_ARRAY(:X1, :Y1, :X2, :Y2)))='TRUE')