/**
 * @name 126780189584211
*/
SELECT T_DELAWARE_NATURAL_1.DELAWARE_NATURAL_ID, T_DELAWARE_NATURAL_1.THE_GEOM, T_DELAWARE_NATURAL_1.NAME, T_DELAWARE_NATURAL_1.TYPE FROM DELAWARE_NATURAL T_DELAWARE_NATURAL_1 WHERE :PARAM1=T_DELAWARE_NATURAL_1.TYPE