/**
 * Do not edit this file manualy, it will be overwritten by Platypus Application Designer.
 */
if (!platypus) {
	var platypus = {};
}
platypus.ready = function() {
	require(['ORM_Test_View'], function(){
		var f = new ORM_Test_View();
		f.show();
	});
};
